version: '3.2'
services:
        dhcp:
                build: ./dhcp
                env_file: ./env
                volumes:
                        - ./data/dhcp:/data
                network_mode: "host"
        dhcp6:
                build: ./dhcp6
                env_file: ./env
                volumes:
                        - ./data/dhcp6:/data
                network_mode: "host"
        dnsmasq:
                build: ./dnsmasq
                env_file: ./env
                volumes:
                        - ./data/dnsmasq:/data
                        - ./data/tftproot:/srv/tftproot:ro
                network_mode: "host"
        lihgttpd:
                build: ./lighttpd
                env_file: ./env
                volumes:
                        - ./data/lighttpd/:/conf:ro
                        - type: bind
                          source: ./data/www/htdocs
                          target: /srv/www/htdocs
                          read_only: "yes"
                network_mode: "host"
